table 'Data Dia Anterior'
	lineageTag: d3bb9d3a-2c27-4384-a95f-7c289a7a43ae

	measure 'Valor Data Dia Anterior' = SELECTEDVALUE('Data Dia Anterior'[Data Dia Anterior])
		formatString: 0
		lineageTag: 57f70b0b-c28c-4b48-811b-62dbb101db98

	column 'Data Dia Anterior'
		formatString: 0
		lineageTag: 14def2f3-370a-4485-8d28-11d86b0f6efc
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Data Dia Anterior' = calculated
		mode: import
		source = GENERATESERIES(0, 1, 1)

	annotation PBI_Id = 34a938bb087d419ab2822242441b7c59

