table Parâmetro
	lineageTag: b3a2b019-4558-4d02-9b75-d119cd6c4073

	measure 'Valor Parâmetro 3' = SELECTEDVALUE('Parâmetro'[Parâmetro], 10)
		formatString: 0
		lineageTag: 5535f946-5c36-479f-8ee7-67ec52193347

	column Parâmetro
		formatString: 0
		lineageTag: 2efda7d4-cd31-4ffd-8679-e983fc1aa9dc
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition Parâmetro = calculated
		mode: import
		source = GENERATESERIES(1, 30, 1)

	annotation PBI_Id = dc6b40d3d2e64a69832f2e3c1898d053

