table vw_dim_origens
	lineageTag: 72d27360-6025-469e-acf4-bf598b82cd07

	column origem_do_contato_agrupada
		dataType: string
		lineageTag: 492f400b-1a7e-40d2-b6fd-76942a2e6e51
		summarizeBy: none
		sourceColumn: origem_do_contato_agrupada

		annotation SummarizationSetBy = Automatic

	column origem_do_contato
		dataType: string
		lineageTag: 789dfb53-acc8-416e-a4d8-b36ebea66410
		summarizeBy: none
		sourceColumn: origem_do_contato

		annotation SummarizationSetBy = Automatic

	column origem_do_contato_agrupada_final
		dataType: string
		lineageTag: baa56fce-e413-43c6-910e-e28a922f80d9
		summarizeBy: none
		sourceColumn: origem_do_contato_agrupada_final

		annotation SummarizationSetBy = Automatic

	partition vw_dim_origens = m
		mode: import
		queryGroup: DEPARA
		source = ```
				let    
				Fonte = Value.NativeQuery(GoogleBigQuery.Database([BillingProject="plancomercial"]){[Name="plancomercial"]}[Data], "SELECT * FROM plancomercial.Static_Data.tb_dim_origem", null, [EnableFolding=true]),
				
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(Fonte,{{"origem_do_contato_agrupada", Text.Proper, type text}, {"origem_do_contato", Text.Proper, type text}, {"origem_do_contato_agrupada_final", Text.Proper, type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Colocar Cada Palavra Em Maiúscula", {"origem_do_contato"})
				in
				    #"Duplicatas Removidas"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

