table vw_investimento_detalhado
	lineageTag: 43066c41-9581-4089-9d7e-7b28af30f846

	column DATA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 9a127270-935a-4d21-ba09-7e82516ff100
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column campaign_status
		dataType: string
		lineageTag: 22b9a749-a597-4dfc-99a9-c42cff5948cc
		summarizeBy: none
		sourceColumn: campaign_status

		annotation SummarizationSetBy = Automatic

	column total_impressoes
		dataType: int64
		formatString: 0
		lineageTag: 5b639246-129e-4f23-8c9c-c55c66e7bd58
		summarizeBy: sum
		sourceColumn: total_impressoes

		annotation SummarizationSetBy = Automatic

	column total_clicks
		dataType: int64
		formatString: 0
		lineageTag: 3f74475f-e475-48c5-aa97-b5a7c68dc44d
		summarizeBy: sum
		sourceColumn: total_clicks

		annotation SummarizationSetBy = Automatic

	column total_clicks_convertidos
		dataType: double
		lineageTag: 1ad3d4cb-8abe-4b03-ace5-cd72016babbb
		summarizeBy: sum
		sourceColumn: total_clicks_convertidos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_custo_medio_por_click
		dataType: double
		lineageTag: f21a2602-9896-4077-a499-60e2f59a7fca
		summarizeBy: sum
		sourceColumn: total_custo_medio_por_click

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_custo_por_clicks_convertidos
		dataType: double
		lineageTag: d020625e-9678-4510-9e27-5679ad39390d
		summarizeBy: sum
		sourceColumn: total_custo_por_clicks_convertidos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_custo
		dataType: double
		lineageTag: b0aa8894-deeb-42da-b4a1-0d0fd656e478
		summarizeBy: sum
		sourceColumn: total_custo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column utm_campaign
		dataType: string
		lineageTag: edeaea55-d104-4ba3-b0fe-52de342e17f0
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column utm_campaign_agrupada
		dataType: string
		lineageTag: 6abdbdec-0c4e-4550-aba5-1b5770c28580
		summarizeBy: none
		sourceColumn: utm_campaign_agrupada

		annotation SummarizationSetBy = Automatic

	column regiao
		dataType: string
		lineageTag: b4042ef4-3024-447e-bd06-08c7b59fcd39
		summarizeBy: none
		sourceColumn: regiao

		annotation SummarizationSetBy = Automatic

	partition vw_investimento_detalhado = m
		mode: import
		source =
				let
				    Fonte = Value.NativeQuery(GoogleBigQuery.Database([BillingProject="plancomercial"]){[Name="plancomercial"]}[Data], "SELECT * FROM plancomercial.modelo.vw_investimento_detalhado", null, [EnableFolding=true]),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(Fonte,{{"utm_campaign", Text.Proper, type text}, {"utm_campaign_agrupada", Text.Proper, type text}, {"regiao", Text.Proper, type text}, {"campaign_status", Text.Proper, type text}})
				in
				    #"Colocar Cada Palavra Em Maiúscula"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

